name: ic2 # you probably want to 'snapcraft register <name>'
version: '2.2.8.188' # just for humans, typically '1.2+git' or '1.3.2'
summary: The package contains industrial craft 2 server. # 79 char long summary
description: |
  This is snap version of industrial craft 2 server for minecraft 1.12.2. Before use open ~/snap/ic2/current/server.properties and set your ip addres. 

grade: stable 
confinement: strict 
base: core18

parts:
  ic2:
    # See 'snapcraft plugins'
    plugin: dump
    source: src
    stage-packages:
      - libfreetype6
      - libpng16-16
      - openjdk-8-jdk
      - openjdk-8-jre
      - openjdk-8-jre-headless
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
    override-stage: |
      snapcraftctl stage
      chmod 777 -R "$SNAPCRAFT_STAGE"

    after:
      - ic2-wraper


  ic2-wraper:
    # See 'snapcraft plugins'
    plugin: dump
    source: scripts
    
apps:
  ic2:
    command: start.sh
    plugs:
      - home
      - network
    environment:
      PATH: '$SNAP:$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH'
      LD_LIBRARY_PATH: '$SNAP_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu'
  
    
